version: "3.8"

networks:
  mainNetwork: {}

services:
  database:
    command: --default-authentication-plugin=mysql_native_password
    build: ./database
    container_name: socialbook-mysqldb
    ports:
      - 8030:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - mainNetwork
  
  server:
    build: ./server
    container_name: socialbook-server
    ports:
      - 8031:8000
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    networks:
      - mainNetwork

  frontend:
    build: ./frontend
    container_name: socialbook-frontend
    command: dev # "prod" for production, "dev" for dev
    ports:
      - 8032:8001
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - server
    restart: on-failure
    networks:
      - mainNetwork